theme = "showfolio"
languageCode = "ja-jp"
baseurl = "https://vr.till0196.com"
title = "Till0196 VR Profile"


[params]
  name = "Till0196 VR Profile"
  description = "Till0196がVRChatとかでやってることをまとめたプロフィールサイト"
  images = "/photo.png"
  author = "Till0196"
  authorEmail = "name@example.com"
  authorImage = "/photo.png"
  autoDarkMode = true
  mainSections = "note"

  favicon = "favicon.ico"
  copyright = "Copyright © 2021 - Till0196 · All rights reserved"

[params.homepage]
  title = "ラスクちゃんはカワイイ"
  tagline = "Till0196"
  description = "のんびりまったり"
  about = "/about"

#[params.homepage.codepen]
#  username = "apvarun"
#  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.social]
  twitter = "https://twitter.com/till0196_vrchat"
  twitter2 = "https://twitter.com/till0196"
  instagram = "https://www.instagram.com/till0196/"
  github = "https://github.com/Till0196"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = "true"
